import Navigation from "../components/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {/* always render layout first! */}
        <Navigation />
        {/* pages = children props */}
        {children}
      </body>
    </html>
  );
}
